site_name: Squad 04
theme:
  #name: dracula
  name: material
nav:
  - Home: index.md
  - Ideação: ideacao.md
  - Arquitetura: arquitetura.md
  - Tecnologias: tecnologias.md
  - Miro: miro.md
  - Atas:
    - ata-modelo: Atas/ata-modelo.md
    - ata-23-03: Atas/ata-23-03.md
    - ata-26-03: Atas/ata-26-03.md
    - ata-04-04: Atas/ata-04-04.md
    - ata-09-04: Atas/ata-09-04.md
    - ata-11-04: Atas/ata-11-04.md
    - ata-16-04: Atas/ata-16-04.md
    - ata-23-04: Atas/ata-23-04.md
    - ata-30-04: Atas/ata-30-04.md
    - ata-02-05: Atas/ata-02-05.md
    - ata-07-05: Atas/ata-07-05.md
    - ata-09-05: Atas/ata-09-05.md
    - ata-14-05: Atas/ata-14-05.md
    - ata-16-05: Atas/ata-16-05.md
    - ata-21-05: Atas/ata-21-05.md
    - ata-28-05: Atas/ata-28-05.md
    - ata-31-05: Atas/ata-31-05.md
    
  - Sprints:
    - Sprint 0: Sprints/sprint0.md
    - Sprint 1: Sprints/sprint1.md
    - Sprint 2: Sprints/sprint2.md
    - Sprint 3: Sprints/sprint3.md
    - Sprint 4: Sprints/sprint4.md
    - Sprint 6: Sprints/sprint6.md

